spring.application.name=sistema-editais
server.port=8080

spring.datasource.url=jdbc:h2:mem:sistema_editais_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin

# O 'update' cria as tabelas automaticamente baseado nas suas classes Java
spring.jpa.hibernate.ddl-auto=update

# Mostra no log do console os comandos SQL sendo executados
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console